### PR TITLE
[2.x] Create parent dir(s) if necessary, do not try to create an existing dir (module unzip)

### PR DESCRIPTION
**Pull request by msoute**
Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=466820

### CODE REVIEW

**Comment by purplefox** [comment]
Hi folks, was this updated to take into account @felfert 's comments?

**Comment by purplefox** [comment]
I believe this is fixed with https://github.com/eclipse/vert.x/commit/64ffa5a632995077f5ac5b3d6cbcb3aa75dee90f

**Comment by msoute** [comment]
Sorry, on vacation this week. Guess i don't need tot check anymore ;-)

**Comment by purplefox** [comment]
Any chance you could quickly sanity check my fix above?

I would like to cut a release today.

**Pull request closed without merging**
