### PR TITLE
close all verticles

### PR DESCRIPTION
**Pull request by fmarinelli**
Close all verticles on test HATest.

### CODE REVIEW

**Comment by cescoffier** [comment]
It looks like you didn't sign the Eclipse CLA.

**Comment by cescoffier** [comment]
How is that related to jgroups (you wrote that It makes the vertx jgroups fail).

**Comment by vietj** [comment]
I think it makes jgroups HA tests fail.

**Comment by cescoffier** [comment]
Oh, by inheritance, ok make sense.

**Comment by purplefox** [comment]
I think what Fabio is trying to say is that, *without* this fix, JGroups cluster tests fail, not that this makes JGroups hazelcast fail.

I'll just add it manually it's just a few characters.

**Comment by fmarinelli** [comment]
Thanks Tim.

I'll sign the Eclipse CLA

On Thu, Sep 3, 2015 at 9:15 AM, Tim Fox <notifications@github.com> wrote:

> I think what Fabio is trying to say is that, *without* this fix, JGroups
> cluster tests fail, not that this makes JGroups hazelcast fail.
>
> I'll just add it manually it's just a few characters.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipse/vert.x/pull/1125#issuecomment-137357523>.
>



-- 
Fabio Marinelli
Software developer
LinkedIn: http://www.linkedin.com/in/fmarinelli
Twitter @fmarinelli

**Pull request closed without merging**
