### PR TITLE
Allow configuration to force close sockets on HttpClientRequest exceptions.

### PR DESCRIPTION
**Pull request by ddimensia**
Relates to #1218 

I'm not sure if this is the best approach as it exposes the ability to close a socket connection via a HttpClientRequest object.  In some cases this may actually be desirable but I could see the incorrect use of the method causing issues also.

I added configuration in HttpClientOptions to enable this feature, it's off by default to maintain backwards compatibility but ultimately I believe the default behavior should be to have it enabled.  See the associated issue for an explanation of the problems caused by the default behavior.

It should be noted that we're running a patched version a 2.1.x that includes effectively the same change (the HTTP2 changes caused it to be implemented differently) in our production environment (multiple apps with high request volumes) and haven't seen any issues.

### CODE REVIEW

**Comment by vietj** [comment]
that's something you cannot do on your own with an exception handler ?

**Comment by ddimensia** [comment]
Well, currently there is no method to force close a connection, just adding a close method to the request interface would make that a possibility.  However, if you read the explanation in the associated issue you would see that the current behavior has some bad side effects and I'm unaware of any advantages.

**Comment by ddimensia** [comment]
Updated with latests master to deal with merge conflicts.

**Comment by vietj** [comment]
hi, I've added this PR that gives more connection access for HTTP/1 https://github.com/eclipse/vert.x/pull/1424 I think you could implement this feature using the HttpConnection

**Pull request closed without merging**
