### PR TITLE
Grammatical fixes in README.

### PR DESCRIPTION
**Pull request by adjohnson916**

### CODE REVIEW

**Comment by pmlopes** [comment]
Hello,

In order to contribute you must have signed the eclipse CLA: http://www.eclipse.org/legal/CLA.php

And then re-submit the PR and don't forget to commit and sign-off:

```
git commit -s -a -m "Grammatical fixes in README"
```

You only need to sign the CLA once for all Eclipse projects :)

**Comment by vietj** [comment]
done it myself

**Comment by adjohnson916** [comment]
@vietj @pmlopes Thanks. I often have trouble with CLAs when they ask me to commit with my email address, since I use [GItHub's private email feature](https://help.github.com/articles/keeping-your-email-address-private/). Is that strictly necessary with Eclipse projects?

**Comment by pmlopes** [comment]
@adjohnson916 yes for all eclipse projects you need to sign their CLA and sign off all your commits. Your email will be public however if you are concerned about your privacy you can always create a specific "commiter" email. that you use only for this kind of things.

The reason is that eclipse will run IP validation checks on all code so they need to assert that the code you wrote is not copied or was copied from another place with an incompatible license. It is a necessary evil that allows us to use open source and not be sued for copyright infringements and the likes.

**Pull request closed without merging**
