### PR TITLE
Bump versions to latest libs as of 12 Feb 2016 - Tests pass

### PR DESCRIPTION
**Pull request by karianna**
Signed-off-by: Martijn Verburg <martijnverburg@gmail.com>

### CODE REVIEW

**Comment by karianna** [comment]
As discussed on the mailing list.  Bumping the versions in core introduces no breakages on core but may conflict with child 'modules' as Vert.x has a flat Classpath.  I'll shortly post a possible Maven plugin detection solution for checking this.

**Comment by karianna** [comment]
At jClarity we use the Ning plugin (https://github.com/ning/maven-dependency-versions-check-plugin) to detect conflicts for dependencues.  The Ning website discusses the 3 resolution techniques you can use to keep your project sane

Maven configuration. In the plugin Management section we have:

```
...
                <plugin>
                    <groupId>com.ning.maven.plugins</groupId>
                    <artifactId>maven-dependency-versions-check-plugin</artifactId>
                    <version>2.0.2</version>
                    <configuration>
                        <failBuildInCaseOfConflict>true</failBuildInCaseOfConflict>
                    </configuration>
                    <executions>
                        <execution>
                            <phase>verify</phase>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
...
```

And in the plugins section for each project you want ning to operate in you can add (Ning was so good we actually simply declared this in the parent project which all children inherited):

```
...
            <plugin>
                <groupId>com.ning.maven.plugins</groupId>
                <artifactId>maven-dependency-versions-check-plugin</artifactId>
            </plugin>
...
```

**Comment by karianna** [comment]
I may have told a lie :-).  I'm seeing an intermittent failure:

```
Failed tests:
  HttpTest.testClientContextWithPipelining:4240->testClientContext:4270->AsyncTestBase.awaitLatch:592->AsyncTestBase.assertTrue:372 null
```

As typical in these cases this is not repeatable :-/

**Comment by cescoffier** [comment]
@karianna - I've updated the dependencies. Could you check ? 

The ning plugin is declared in the parent (and is pretty cool, thanks !).

**Comment by karianna** [comment]
Looks good to me, I'll close my PR.

Cheers,
Martijn

**Comment by karianna** [comment]
Superseded by #1311

**Pull request closed without merging**
