### PR TITLE
Some changes to ClusterSerializable and added UTF8 to Utils

### PR DESCRIPTION
**Pull request by purplefox**

### CODE REVIEW

**Comment by purplefox** [comment]
@vietj please review

**Comment by kuujo** [comment]
@purplefox rather than adding a UTF-8 constant to Utils, why not use StandardCharsets?

http://docs.oracle.com/javase/7/docs/api/java/nio/charset/StandardCharsets.html

**Comment by purplefox** [comment]
Didn't know that existed. Thanks!

**Comment by vietj** [comment]
looks good to me

**Pull request merged**
