### PR TITLE
Refactor net base for pipeline

### PR DESCRIPTION
**Pull request by vietj**
This pull request changes the internal api to extend TCP client and server. Previously one had to use inheritance, this new one exposes instead a `NetSocketInternal` that allows to read/write any pipeline message and modify the channel pipeline.

### CODE REVIEW

**Comment by vietj** [comment]
can you check if there are any Netty errors ?

**Comment by ppatierno** [comment]
what do you mean by Netty errors ?

**Comment by vietj** [comment]
I mean review the quality of the code :-)

**Comment by vietj** [comment]
and I know you know Netty :-)

**Pull request merged**
