### PR TITLE
Mapping added for woff2 files following the latest W3C recommendation 

### PR DESCRIPTION
**Pull request by leolux**
Spec: 15 March 2016 (https://www.w3.org/TR/WOFF2/#IMT)
PR for the issue: https://github.com/eclipse/vert.x/issues/1440

### CODE REVIEW

**Comment by vietj** [comment]
Hi @leolux you need to sign the Eclipse CLA.

**Comment by leolux** [comment]
Ok thanks! 
I have successfully signed the Eclipse CLA. How to repeat the validation check? Or do I have to make another pull request?

**Comment by vietj** [comment]
yes and sign the commit please

**Comment by vietj** [comment]
maybe a push --force in this branch could work ?

**Comment by pmlopes** [comment]
Fixes #1440

**Pull request closed without merging**
