### PR TITLE
Calling resume in an AsyncFile endHandler will cause a new call to th…

### LINKED ISSUE #1890: Calling resume in an AsyncFile endHandler will cause a new call to the endHandler

### PR DESCRIPTION
**Pull request by vietj**
…e endHandler - fixes #1890

### CODE REVIEW

**Comment by vietj** [comment]
please review @tsegismont @pmlopes @cescoffier

**Comment by vietj** [comment]
anyone fancy a review @tsegismont @pmlopes @cescoffier ?

**Comment by tsegismont** [comment]
How does the test make sure the endHandler is not called twice?

**Comment by vietj** [comment]
for some reason it is missing a commit

**Comment by vietj** [comment]
actually no, this PR was already merged a week ago (reviewed by Clement) and this is a commit to improve the test only. So no need to review. (https://github.com/eclipse/vert.x/commit/309188b2f749997653481e2e6ca64fa33607a211#diff-d0eff6d59507e6aeafa9dcfff6a70143)

**Pull request merged**
