### PR TITLE
changes AsyncResult.map() and .otherwise() contracts 

### PR DESCRIPTION
**Pull request by ruslansennov**
towards #2158

### CODE REVIEW

**Comment by vietj** [comment]
please only keep the AsyncResult implementation and not add new factory method to not provide two ways of doing the same thing. People are used to the idiom Vertx.succeededFuture() to build an immutable AsyncResult and that's fine this way.

**Comment by vietj** [comment]
however you can remove the map default method I think as the impl is lazy and reimplement them correctly in SucceededFuture/FailedFuture in a non lazy fashion

**Comment by ruslansennov** [comment]
> you can remove the map default method

OK, it will be a new PR, but in this case all tests in `FutureTest` related to the `AsyncResult` do not make sense and can be deleted, right?

**Comment by ruslansennov** [comment]
> you can remove the map default method

It is not works for uncompleted futures, because Future can has only one handler and this case will not work

```
    AsyncResult<Integer> map1 = f.map(String::length);
    AsyncResult<Integer> map2 = f.map(17);
```

So, if new static factories are undesirable, we must leave everything as is

**Comment by vietj** [comment]
I mean that in `AsyncResult` you can remove the default implementation of the map method but keep the method.

**Comment by vietj** [comment]
I mean this https://github.com/vietj/vert.x/commit/58238bc3ebb559cabf76c92ca6328bd49588f625

**Pull request closed without merging**
