### PR TITLE
2.x custom monitoring and mem leak fix

### PR DESCRIPTION
**Pull request by nevesmarcio**
This contribution enriches the eventbus with a few monitoring facilities:
* Added the possibility to pass a EventBusHook to the EventBus object listening the following events: beforeReceive, delivered and afterReceive
* SockJSSocket interface extended so that we can monitor the trasport type for the established channel between client and eventbus
* Memory leak fix in the subscribers cache

### CODE REVIEW

**Comment by purplefox** [comment]
Hi, can you keep the memory leak fix in separate PRs than other changes please?

Also, can you sign the CLA etc, as explained on the wiki?

**Comment by purplefox** [comment]
@nevesmarcio ping

**Comment by nevesmarcio** [comment]
Hi Tim,
I will do as you are suggesting:
- sign the CLA
- split the memory leak fix and the monitoring changes into two different PR

I'm just a bit overburdened with work currently, but will do it asap.

**Comment by nevesmarcio** [comment]
Will now close this pull request and create new ones.

**Pull request closed without merging**
