### PR TITLE
Support switching to netty transport epoll in GNU/Linux, significantly improve performance

### PR DESCRIPTION
**Pull request by vertxer**
1), Vert.x 3.0 use nio socket transport, nio have more feature, such as Multicast, but nio's performance is low. http://netty.io/wiki/native-transports.html

2), When I change nio to epoll in GNU/Linux, the performance significantly improved. Send 90000 1k messages time-consuming reduced to 25%. As follows:
`
Send machine: i7 4790, 32G RAM, 256G SSD, 1G Lan, CentOS 6.5, Java8;
Receive machine: i7 4790, 32G RAM, 256G SSD, 1G Lan, Gentoo, Java8;
90000 message, 1KB/message.

netty nio:
receive data: index is 2 (10000 message) , interval time is 2107 ms
receive data: index is 3 (10000 message) , interval time is 1785 ms
receive data: index is 4 (10000 message) , interval time is 2477 ms
receive data: index is 5 (10000 message) , interval time is 4083 ms
receive data: index is 6 (10000 message) , interval time is 4288 ms
receive data: index is 7 (10000 message) , interval time is 5127 ms
receive data: index is 8 (10000 message) , interval time is 5068 ms
receive data: index is 9 (10000 message) , interval time is 5563 ms
receive data: index is 10 (10000 message) , interval time is 5178 ms

netty epoll:
receive data: index is 2 (10000 message) , interval time is 985 ms
receive data: index is 3 (10000 message) , interval time is 998 ms
receive data: index is 4 (10000 message) , interval time is 1001 ms
receive data: index is 5 (10000 message) , interval time is 990 ms
receive data: index is 6 (10000 message) , interval time is 1009 ms
receive data: index is 7 (10000 message) , interval time is 1016 ms
receive data: index is 8 (10000 message) , interval time is 1009 ms
receive data: index is 9 (10000 message) , interval time is 997 ms
receive data: index is 10 (10000 message) , interval time is 1271 ms
`

3) I wrote NettyTransportFactory class for swtich nio/epoll/possible anything in the future, and NettyTransportFactoryTest class. All testcase successed.

4) Now any user can pass nettyTransport args to vert.x in GNU/Linux, enable epoll, enjoy high performance.

Signed-off-by: Mike Bai <lostitle@gmail.com>

### CODE REVIEW

**Comment by vertxer** [comment]
When I squash 3 commit in this patch, commit operational confusion. So I re-fork project, and create this new pull request.

**Comment by vertxer** [comment]
how can I do anything for this patch?

**Comment by purplefox** [comment]
Hi Mike,

I did some tests on our servers using wrk using epoll transport, and it actually worked out a bit slower than the normal nio transport, so I don't consider this high priority at the moment, but it would be nice to support epoll in the future.

Also I have a set of performance optimisation due to be merged in master soon and these aren't currently compatible with the epoll transports, see 

https://github.com/netty/netty/issues/3897#issuecomment-113067419

So I'm going to leave this PR for now.

**Comment by vertxer** [comment]
@purplefox  Thanks for your reply.   I am going to re-test result and confirm again under different scenarios.

**Comment by mixja** [comment]
I'm a bit confused - as per https://docs.oracle.com/javase/8/docs/technotes/guides/io/enhancements.html#jdk6 since Java 1.6:

*A new java.nio.channels.SelectorProvider implementation that is based on the Linux epoll event notification facility is included. The epoll facility is available in the Linux 2.6, and newer, kernels. The new epoll-based SelectorProvider implementation is more scalable than the traditional poll-based SelectorProvider implementation when there are thousands of SelectableChannels registered with a Selector. The new SelectorProvider implementation will be used by default when the 2.6 kernel is detected. The poll-based SelectorProvider will be used when a pre-2.6 kernel is detected.*

So this would imply epoll is used on Linux 2.6+ systems automatically...and the Vert.x NioEventLoopGroup creation code reads:

```
eventLoopGroup = new NioEventLoopGroup(options.getEventLoopPoolSize(),
                                       new VertxThreadFactory("vert.x-eventloop-thread-", checker, false));
```

which means the default SelectorProvider is used as per http://netty.io/4.0/api/io/netty/channel/nio/NioEventLoopGroup.html

**Comment by mixja** [comment]
To add to this, calling SelectorProvider.provider() to get the default system provider:

- On OS X returns ```sun.nio.ch.KQueueSelectorProvider```
- On Linux returns ```sun.nio.ch.EPollSelectorProvider```

**Comment by kuujo** [comment]
Netty has `Epoll.isAvailable()` as well:
```java
if (Epoll.isAvailable()) {
  eventLoopGroup = new EpollEventLoopGroup(...);
} else {
  eventLoopGroup = new NioEventLoopGroup(...);
}
```

**Comment by mixja** [comment]
@kuujo - if Nio detects the most optimal selector provider, what is the benefit of the EpollEventLoopGroup?

**Comment by kuujo** [comment]
@mixja Ahh, you're right. The docs you referenced do add up and seem to imply that Epoll is used on systems where it's available. That makes @vertxer's benchmarks curious, and this issue a bit above my pay grade :-P

**Comment by purplefox** [comment]
Closing this for now.

Please reopen if things change.

**Pull request closed without merging**
