### PR TITLE
#1815 - Created tests for trustManagerFactoryFix

### PR DESCRIPTION
**Pull request by domhauton**
Creating tests to ensure engineInit called before engineGetTrustManagers

Signed-off-by: domhauton@gmail.com
Signed-off-by: Dominic H <domhauton@gmail.com>

### CODE REVIEW

**Comment by vietj** [comment]
@domhauton so looking at it, the TrustOptions should itself initialize the `TrustManagerFactory` in the `getTrustManagerFactory` method. That's what the other implementation do. For instance `KeyStoreHelper#getTrustMgrFactory`:

```
  public TrustManagerFactory getTrustMgrFactory(VertxInternal vertx) throws Exception {
    TrustManagerFactory fact = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
    KeyStore ts = loadStore(vertx);
    fact.init(ts);
    return fact;
  }
```

They should do it, because the TrustOptions implementation is supposed to have access to the `KeyStore` and can do it. The `SSLHelper` cannot.

I will update the documentation to mention that the returned factory is assumed to be initialized.

**Comment by domhauton** [comment]
I have updated the test to reflect the change - However, I do think it would be useful if you could setKeyStore in TrustOptions to make it obvious to users. If it's not set then it should load the default keystore. Thoughts?

**Comment by vietj** [comment]
@domhauton that would create issues with other pre-initiliazed options like the one I mentionned.

However I've added a new tests that checks that TrustOptions can be used to validate this SPI : https://github.com/eclipse/vert.x/commit/3034cfdb10735acc48281209d79383733cabf7f5

so I think your PR should not be necessary anymore, as the test added in HttpTLSTest does the same but with a full TLS usage.

**Comment by vietj** [comment]
i.e https://github.com/eclipse/vert.x/commit/3034cfdb10735acc48281209d79383733cabf7f5#diff-607c245648ec2e1e7226237a0ef45113R365

**Comment by domhauton** [comment]
@vietj Any thoughts on this?

This solves the issue neatly for anyone that wants to add their own Trust Managers.

**Comment by vietj** [comment]
@domhauton I prefer users come up with their own impl for TrustOptions as it's quite trivial to implement

**Comment by domhauton** [comment]
No need for basic TrustManager Implementation

**Pull request closed without merging**
