### PR TITLE
exposed the number of instances of a verticle that were started

### PR DESCRIPTION
**Pull request by jtruelove**
Signed-off-by: Jeremy Truelove <jtruelove@gmail.com>

### CODE REVIEW

**Comment by purplefox** [comment]
Jeremy,

DeploymentTest is probably a good place :)

Also, can you two spaces for tabs, not four?

**Comment by jtruelove** [comment]
also in the case of a null deployment or no deployment options should the function return 1 or 0? Currently it's 0 but it should probably be implicitly 1 I'd think.

**Comment by jtruelove** [comment]
updated with tests

**Comment by jtruelove** [comment]
I can also re-branch and submit the pull so the checkin comments aren't janked, I tried remote amending a commit like a newb.

**Comment by jtruelove** [comment]
new pull request here exposed the number of instances of a verticle that were started

**Pull request closed without merging**
