### PR TITLE
Getting corresponding sharred map

### PR DESCRIPTION
**Pull request by nolequen**
Sometimes it is very uncomfortable to choose an appropriate map explicitly, especialy if we don't know in advance whether the Vert.x instance clustered or not. E.g. when writing tests which may use cluster in some cases or not, choosing the "right" map leads to changes in production code.

The goal of the proposed changes is to make it easier to work with shared data without paying attention if the instance is clustered or not.

### CODE REVIEW

**Comment by vietj** [comment]
it looks ok to me, however I think we should honour the TTL with a timer and make sure it works correctly.

**Comment by nolequen** [comment]
Great! I will add TTL support at an early date.

**Comment by nolequen** [comment]
@vietj I have updated the request with TTL support.
Unfortunately, some merge-commits were added... Is it ok or new request should be created?

**Comment by nolequen** [comment]
Replaced with up-to date request: #2244.

**Pull request closed without merging**
