### PR TITLE
more toJson() methods

### PR DESCRIPTION
**Pull request by ruslansennov**
Force pushed

### CODE REVIEW

**Comment by vietj** [comment]
these methods should be tested, there are tests for these classes

**Comment by ruslansennov** [comment]
@vietj also found bug in codegen for converters.

See `PemTrustOptionsConverter`
```java
    if (obj.getCertValues() != null) {
      json.put("certValues", new JsonArray(
          obj.getCertValues().
              stream().
              map(item -> item.getBytes()).
              collect(java.util.stream.Collectors.toList())));
    }
```
here certificates added as byte arrays but not as base64 encoded strings

**Comment by ruslansennov** [comment]
@vietj tests added, bug fixed. Now lists generate in the same manner as maps

**Comment by vietj** [comment]
@ruslansennov we need also test for other options such HttpClientOptions, etc...

**Comment by ruslansennov** [comment]
**Already tested**
* generated/io/vertx/core/DeploymentOptionsConverter.java
* generated/io/vertx/core/dns/AddressResolverOptionsConverter.java
* generated/io/vertx/core/net/PemTrustOptionsConverter.java
* java/io/vertx/core/net/JksOptions.java
* java/io/vertx/core/net/PemKeyCertOptions.java
* java/io/vertx/core/net/PemTrustOptions.java
* java/io/vertx/core/net/PfxOptions.java
* java/io/vertx/core/net/ProxyOptions.java

**Tests added**
* generated/io/vertx/core/cli/OptionConverter.java

**TODO**
* generated/io/vertx/core/eventbus/EventBusOptionsConverter.java
* generated/io/vertx/core/http/HttpClientOptionsConverter.java
* generated/io/vertx/core/http/HttpServerOptionsConverter.java
* generated/io/vertx/core/net/ClientOptionsBaseConverter.java
* generated/io/vertx/core/net/TCPSSLOptionsConverter.java

Last 5 converters have broken serialization/deserialization mechanism because `TCPSSLOptions` have two problem fields: 
```java
  private KeyCertOptions keyCertOptions;
  private TrustOptions trustOptions;
```
Both fields are interfaces and can’t be serialized by current converters properly. I believe this is not this issue and should be fixed in own PR.

**Pull request merged**
