### PR TITLE
Fix missing pass logging arguments on slf4j delegate

### PR DESCRIPTION
**Pull request by zcx2001**
#1208 new fix

### CODE REVIEW

**Comment by zcx2001** [comment]
How to accept this Agreement？

**Comment by vietj** [comment]
this is explained here https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md

**Comment by cescoffier** [comment]
@vietj this PR can be closed, as it was fixed in 3.2.1.

**Comment by cescoffier** [comment]
(closed and marked as invalid or duplicate)

**Pull request closed without merging**
