### PR TITLE
HTTP server connection keeps processing pending pipelined requests

### PR DESCRIPTION
**Pull request by vietj**
Fix for #2365

### CODE REVIEW

**Comment by vietj** [comment]
@tsegismont the server connections receives pipelined requests messages (HttpRequest, HttpLastContent, HttpRequest, etc...)

The first requests does not end the first response the field `pendingResponse` remains assigned. and it closes the connection.

When the second requests arrives (it arrives in the same channel read operation since it's pipelined and aggregated at the TCP level) then `processMessage(Object)` returns false and the request object is enqueued. Asynchronous the first processing  message triggered a call to `checkNextTick()`, when the asynchronous `checkNextTick()` runs it tries to process the message and fails since `pendingResponse ` is still assigned, the message is put back on the queue and since the queue is not empty `checkNextTick()` is called again and so on.

**Comment by vietj** [comment]
now I'm wondering about the current code:

```
  synchronized void handleMessage(Object msg) {
    if (queueing) {
      enqueue(msg);
    } else {
      if (processMessage(msg)) {
        checkNextTick();
      } else {
        enqueue(msg);
      }
    }
  }
```

that seems correct, but I think that it's not necessary to call `checkNextTick()` if the request process the message, i.e:

```
  synchronized void handleMessage(Object msg) {
    if (queueing) {
      enqueue(msg);
    } else {
      if (processMessage(msg)) {
        // Since we processed the message it means that the queue is empty so we don't need to check the next tick
        checkNextTick();
      } else {
        enqueue(msg);
      }
    }
  }
```

**Comment by vietj** [comment]
so we could have instead

```
  synchronized void handleMessage(Object msg) {
    if (queueing || !processMessage(msg)) {
      enqueue(msg);
    }
  }
```

**Comment by vietj** [comment]
@tsegismont I've updated the PR to not call `checkNextTick()` when a message is processed in `handleMessage(Object)` and improved the related tests

**Comment by vietj** [comment]
the microbenchmark for HTTP server shows significant improvements likely related to the removal of the unecessary `checkNextTick` invocation in `handleMessage`:

### this branch

```
HttpServerHandlerBenchmark.netty     thrpt   10  840.095 ± 132.653  ops/ms
HttpServerHandlerBenchmark.vertx     thrpt   10  649.268 ±  10.494  ops/ms
HttpServerHandlerBenchmark.vertxOpt  thrpt   10  711.100 ±   9.458  ops/ms
```

### master branch

```
HttpServerHandlerBenchmark.netty     thrpt   10  845.225 ± 85.887  ops/ms
HttpServerHandlerBenchmark.vertx     thrpt   10  620.237 ±  9.065  ops/ms
HttpServerHandlerBenchmark.vertxOpt  thrpt   10  690.147 ± 11.093  ops/ms
```

**Comment by tsegismont** [comment]
>@tsegismont the server connections receives pipelined requests messages (HttpRequest, HttpLastContent, HttpRequest, etc...)
>
>The first requests does not end the first response so the field pendingResponse remains assigned and it closes the connection.
>
>When the second requests arrives (it arrives in the same channel read operation since it's pipelined and aggregated at the TCP level) then processMessage(Object) returns false and the request object is enqueued. The first processing message triggered a call to checkNextTick(), when the asynchronous checkNextTick() runs it tries to process the message and fails since pendingResponse is still assigned, the message is put back on the queue and since the queue is not empty checkNextTick() is called again and so on.

I understand that but I can't see why the new test would fail without the fix.

**Comment by vietj** [comment]
ok, so what will fail is not the test itself but the shutdown of the corresponding Vert.x instance because the event loop will continue to process tasks and the vertx.close(Handler<AsyncResult>> will not complete in time.

I can add a note in the test about it.

**Comment by tsegismont** [comment]
>I can add a note in the test about it.

:+1:

**Pull request merged**
