### PR TITLE
notify caller that the cluster manager they requested failed to join

### PR DESCRIPTION
**Pull request by guss77**
Signed-off-by: Oded Arbel <oded@geek.co.il>

Fixes issue #1797

### CODE REVIEW

**Comment by tsegismont** [comment]
Could you add a test to your PR?

**Comment by guss77** [comment]
I can try - setting up the Hazelcast cluster manager to fail wasn't easy for me :smiley: . I'll try to do something for tomorrow - I'm kind of out of time today.

**Comment by tsegismont** [comment]
No worries :)

You shouldn't use a failing Hazelcast cluster manager here. The Vert.x core
project should not be aware of any implementation. You could write your own
mock cluster manager for the test.

2017-02-06 15:21 GMT+01:00 Oded Arbel <notifications@github.com>:

**Comment by guss77** [comment]
Added unit test - I hope I put it in the right place. Its kind of simplistic, and if the bug is not fixed it doesn't "fail" - instead it errors out.

**Comment by tsegismont** [comment]
The test looks good to me. As for its location, I believe it should be
added to io.vertx.test.core.CreateVertxTest, instead
of io.vertx.test.core.VertxTest

Thank you!

2017-02-06 21:35 GMT+01:00 Oded Arbel <notifications@github.com>:

**Comment by guss77** [comment]
@tsegismont - thanks for your comments. I've moved the test as you requested, and I see that `CreateVertxTest` has a facility to create a clustered vertx so I used that. After the change the test still errors out without the fix and passes with the fix.

**Comment by tsegismont** [comment]
Can you revert the changes on io.vertx.test.core.VertxTest ?

**Comment by guss77** [comment]
Oops. Thanks for catching that - automatic tools, what can you do? ;-)

**Comment by tsegismont** [comment]
LGTM, thanks!

2017-02-07 11:14 GMT+01:00 Oded Arbel <notifications@github.com>:

**Pull request merged**
