### PR TITLE
Http client request timeout with hashedWheelTimer

### PR DESCRIPTION
**Pull request by pifuant**

### CODE REVIEW

**Comment by vietj** [comment]
can you explain what is the benefit to use this instead of vert.x timer ?

**Comment by vietj** [comment]
what's your motiviation ? are you experiencing issues ?

**Comment by pifuant** [comment]
@vietj 

I think hashedWheelTimer is better for io timeout, so I make a PR.

**Comment by vietj** [comment]
the actual timers in Vert.x are done on the event loop thread and your current patch uses a timer that has its own thread, so will break the actual concurrent model that expects all tasks to be fired on the same thread

**Comment by pifuant** [comment]
We can modify it  on the event loop thread, what do you think?

**Comment by pifuant** [comment]
https://github.com/netty/netty/blob/48df2f66b858f3ce2a0a069dafb1332da55c47f9/common/src/main/java/io/netty/util/HashedWheelTimer.java#L565

Let the event loop thread timer trigger next tick, not thread sleep.

**Comment by vietj** [comment]
this thread sleep in inherent to the HashedWheelTimer

**Comment by pifuant** [comment]
implement new hashedWheelTimer with  the event loop thread timer driven.

low level ----------------------------------------------> high level
the event loop thread timer  ->  HashedWheelTimer ->   io timeout

**Comment by vietj** [comment]
that's not really possible @pifuant since the event loop thread must not block

**Pull request closed without merging**
