### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by xkr47**
Fix & improve Eclipse CLA acceptance instructions

### CODE REVIEW

**Comment by pmlopes** [comment]
@xkr47 you forgot to sign-off your commit

**Comment by xkr47** [comment]
I commited it directly on github and forgot.. let me fix that..

**Comment by xkr47** [comment]
Force-pushed new version.

**Comment by cescoffier** [comment]
@xkr47 did you sign the Eclipse CLA (https://eclipse.org/legal/CLA.php).
If not, it's a 2 minutes process:

* On the previous page, clic on "sign" (on the left column)
* Create an account
* Follow the sign process (it's just a button).

Your account needs to be associated with the "xkr47@outerspace.dyndns.org" email address (your sign-off address).

**Comment by xkr47** [comment]
Yes I have and I do not intend to make that email public since I use different email addresses for all services. Thanks for your interest.

**Comment by xkr47** [comment]
It does not seem to be possible to associate multiple emails with an account. However I have associated my account with my github account and my github account identifies the email I used.

**Pull request closed without merging**
