### PR TITLE
Added possibility to register custom jackson modules in Json utility class

### PR DESCRIPTION
**Pull request by pjozsef**
Adds the registerModule method to the Json class, so decoding/encoding can be extended with custom serializers/deserializers.

### CODE REVIEW

**Comment by cescoffier** [comment]
If we add registration support, it would be good to have the unregister no ?

We would need unit tests, before integrating this feature.

**Comment by pjozsef** [comment]
@cescoffier as far as I know there is no way in Jackson to unregister a module.
Added tests to make sure the registered module is used for serialization/deserialization.

**Comment by pmlopes** [comment]
This is a common requested feature, jackson does not support unregister of modules and recommends creating a new object mapper. We could however add a method that clear the modules e.g.:

```java
void clearModules() {
  mapper = new ObjectMapper();
  // so we get back to the original state
  initialize();
}
```

**Comment by vietj** [comment]
it would be great to "approve" via github only when all remarks have been done

**Comment by vietj** [comment]
thanks

**Comment by vietj** [comment]
the original repo from which the PR originated is not anymore available, besides the mappers are public and can be modified actually without this patch - closing

**Pull request closed without merging**
