### PR TITLE
Make sure that request.handleException is called only once

### PR DESCRIPTION
**Pull request by testn**
Test added 

Signed-off-by: Testo Nakada test1@doramail.com

### CODE REVIEW

**Comment by testn** [comment]
@vietj test added

**Comment by vietj** [comment]
Actually I don't understand why only a single request should have this exception and not the others in the pipeline

**Comment by testn** [comment]
If the exception happens when the request has not been fully written yet, the error handler will be invoked twice.

**Comment by vietj** [comment]
I've added the test in vertx to ensure the behavior - thanks - I think this was fixed a while ago

**Pull request closed without merging**
