### PR TITLE
Adding support for naming the vert.x instance

### PR DESCRIPTION
**Pull request by ionelMihai**

### CODE REVIEW

**Comment by ionelMihai** [comment]
related to #1255

**Comment by testn** [comment]
It should use the vert.x name to name the event loop and worker thread associated to the vert.x instance.

**Comment by testn** [comment]
@vietj can we get this merged in?

**Comment by vietj** [comment]
not under this form - your use case is about naming threads ?

**Comment by testn** [comment]
Yes. That's right.

**Pull request closed without merging**
