### PR TITLE
Issues/#1956 proxy ftp

### PR DESCRIPTION
**Pull request by alexlehm**
support ftp:// urls for http proxy requests

### CODE REVIEW

**Comment by tsegismont** [comment]
@alexlehm the changes look good to me. However I wonder if we shouldn't update the `web-client` code as well (there is code there similar to what's in `HttpClientImpl.java` to determine the actual port)

**Comment by vietj** [comment]
good point, we should also update the WebClientOptions with 'forceSni'

**Comment by alexlehm** [comment]
@tsegismont i think we should, there is currently no method to create a HttpRequest with a protocol except requestAbs, so WebClient would have to go from abs url to parsed to abs url again, not quite sure what is the sensible solution for this

**Comment by alexlehm** [comment]
@tsegismont I have created the same handling for web-client, I don't like they way this is working, maybe it can be improved

https://github.com/alexlehm/vertx-web/tree/web-client-protocol

**Comment by vietj** [comment]
thanks Alex!

**Comment by tsegismont** [comment]
I am still clearing my email backlog, so maybe you did it already, if not
can you open a PR there?

2017-05-04 23:30 GMT+02:00 Alexander Lehmann <notifications@github.com>:

**Comment by alexlehm** [comment]
@tsegismont commited a small fix now

**Pull request merged**
