### PR TITLE
#1996 Fixed ServerWebSocket reject to return 404

### PR DESCRIPTION
**Pull request by mithunsasidharan**
Signed-off-by: Mithun Sasidharan <mithunsasidharan89@gmail.com>

### CODE REVIEW

**Comment by mithunsasidharan** [comment]
Also, imported the few HttpResponseStatus and single HttpVersion from netty handler instead of all (*)

**Comment by mithunsasidharan** [comment]
@vietj : Can you please review/merge. Thanks.

**Comment by pmlopes** [comment]
Not sure about this. During the handshake if the operation fails I think 502 is correct... 404 doesn't make sense to me since it's an connection handshake not the resource access.

**Comment by vietj** [comment]
@pmlopes good point

**Comment by vietj** [comment]
for HTTP/2 when a h2c upgrade fails, we return a 400 status code

**Comment by vietj** [comment]
imho, I would keep 502 error. In node reject allow to specify a status code and a reject reason

**Comment by vietj** [comment]
the Netty WebSocketServerProtocolHandler also uses 400 status code when it handles a rejected connection

**Comment by mithunsasidharan** [comment]
@vietj : So do we need this change anymore then ?

**Comment by vietj** [comment]
I think we should use 400 code, document it and test it.

it should also added in the list of breaking changes in the wiki.

**Comment by vietj** [comment]
@mithunsasidharan any news for updating this PR ?

**Comment by mithunsasidharan** [comment]
@vietj : will work on it over weekend !

**Comment by vietj** [comment]
@mithunsasidharan there should be a test for this

**Comment by vietj** [comment]
this has been superseded by https://github.com/eclipse/vert.x/pull/2066

**Pull request closed without merging**
