### PR TITLE
SSLSession accessor support to get access to SSL session information

### PR DESCRIPTION
**Pull request by dachaac**
Java SE 5-8 has deprecated usage of SSLSession#getPeerCertificateChain() as described in here:
https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSession.html#getPeerCertificateChain--

This PR adds support for SSLSession#getPeerCertificates() which has new accessor peerCertificates() to follow naming convention for peerCertificateChain(). peerCertificateChain() is left there with @deprecated note to transition to peerCertificate().

TLS test cases are adapted to use peerCertificates().

### CODE REVIEW

**Comment by sauthieg** [comment]
Should Vert.x use the `@Deprecated` annotation (in addition to the doclet) ?

**Comment by vietj** [comment]
I'm wondering if instead we should rather not give access to the SSL session instead of copying all its methods.

**Comment by dachaac** [comment]
@vietj Do you mean to **add** access to SSL Session? It might be better option than having multiple accessors. SSL Session also provides other methods that user might want to use.

- getLocal*() might have some use cases. 
- Part of getPeer*() is already available otherwise but shorthand getPeerPrincipal() might have uses.

Shall I replace peerCertificates() in this PR with sslSession() accessor?
Shall I remove @Deprecated or keep it there? Now instead direct user to sslSession() usage?

**Comment by vietj** [comment]
@dachaac let's go for an `sslSession()` that returns it and no `deprecated` as the original methods are not deprecated on `SSLSession`.

**Comment by dachaac** [comment]
@vietj PR updated for sslSession() and changed wording about deprecation to recommendation.

**Comment by vietj** [comment]
thanks, I don't think it's necessary to change the use of `Certificate` over `X509Certificate` for tests

**Comment by dachaac** [comment]
@vietj Point for the change was to show how to do it with the new interface. Shall the commit be removed from this PR?

**Comment by vietj** [comment]
yes

**Comment by dachaac** [comment]
@vietj test commit removed.

**Comment by vietj** [comment]
@ppatierno we've added this to NetSocket, perhaps that's something you want to expose in a similar fashion in MQTT ?

**Pull request merged**
