### PR TITLE
Various cli improvements

### PR DESCRIPTION
**Pull request by cescoffier**
Some improvement around the CLI system:

* provide multiple argument
* provide 'help' flag to options
* provide validity of command line support
* provide options with choices

### CODE REVIEW

**Comment by vietj** [comment]
looks good to me, will check with vertx-shell and merge it.

**Comment by vietj** [comment]
I don't see how to declare multi valued in `@Argument` annotation, is it implicitly done via `List<String>` detection?

**Comment by vietj** [comment]
Could we have `@Argument()` have `-1` as default value for `index` ? this way we don't have to declare it and the auto numeration would work if it can read the members in right order

**Comment by vietj** [comment]
`List<String>` works but it requires at least one element, I think it should tolerate no values as an empty list is valid for a multivalue.

**Comment by cescoffier** [comment]
When the argument is not set, the "setter" method should not be called. Do you see it called ?

**Comment by vietj** [comment]
ah it's because it is "required"

**Comment by vietj** [comment]
yes working fine, I was expecting that required = true + zero arg => empty list, which does make sense to me. but required = false works fine

**Pull request merged**
