### PR TITLE
Multivalued server cookies should be seen as a single semi colon sepa…

### LINKED ISSUE #1506: Multivalued server cookies should be seen as a single semi colon separated header
### Cross posted issue

https://github.com/vert-x3/vertx-web/issues/412

I apologize, initially i posted this to vertx-web, as i suspected the issue was in  `CookieHandler` code, but now I'm sure the issue is in vertx core code, as http headers parsing is done by vertx-core

### Version

* vert.x core: 3.3.0
* vert.x web: 3.3.0
* SSL and ALPN with netty-tncnative: 1.1.3
* netty: 4.1.1

### Context

If a client got multiple cookies to send in a request, and ALPN is on and the request is issued with HTTP/2, the vert.x server cannot read correctly the cookie header nor the `CookieHandler` works fine.

It gets just one Cookie of many (a random one as they're sent in random order by browser as per specs)

This is due to the fact that Http/2 sends cookies in multiple COOKIE headers and not anymore in a single semicolon separated field.

Please add conversion in a single ; separated header using Netty's  `HttpConversionUtil` as Netty's  has already provided that solution to this issue, see: https://github.com/netty/netty/issues/4457

### Steps to reproduce

1. Enable HTTPS and ALPN on a Vert.x server
2. Use latest version of google chrome and ensure you're negotiating `http/2` (e.g. check with _'http/2 and spdy indicator extension'_)
3. Using the _'cookie inspector extension'_ or whatever, add some cookie name-value pairs to simulate a request with multiple cookies set
4. Refresh the test page and debug if you can get all the test cookie pairs at server using a `CookieHandler` or with a raw `logger.info("All headers "+  new JsonArray(request.headers().entries()).encodePrettily());`
5. You'll get just 1 cookie of the many, if you repeat the request or delete some cookie you can have it in random rotation, but never more than one cookie  per request is readable to vert.x

### Extra

This issue can cause authentication/session issues too

### PR DESCRIPTION
**Pull request by vietj**
…rated header - fixes #1506 

@creativeprogramming can you check with this branch it solves the problem ?
@pmlopes can you review ?

### CODE REVIEW

**Comment by creativeprogramming** [comment]
I'll check soon and let you know, sorry for delay i'm out of office now, will get back to you monday

**Comment by vietj** [comment]
@pmlopes can you have a look too ?

**Comment by pmlopes** [comment]
It seems good to me ( I just took a look at the code, did not run web test suite )

**Comment by creativeprogramming** [comment]
Hi, I checked it using in my apps (my manual testcases) and it seems very good for me: vert.x server is able to read all the cookies with no issue.

I like the solution so this morning I also pushed it in production on a website with some http/2 traffic (where I was running the temporary patch)  and there was no issue until now, of course I'll inform you here if any will come in next days, but I don't think that will be any: from my point of view I already can give you my 'vote' as "it's ready to be merged".

Thanks a lot!

**Comment by vietj** [comment]
thanks for checking @creativeprogramming will be in Vert.x 3.3.3

**Pull request merged**
