### PR TITLE
Issues/#1498 http proxy request

### LINKED ISSUE #1498: Implement HTTP Proxy for non SSL HttpClient
At the moment the HttpClient proxy configuration uses CONNECT for non SSL HttpClient and instead it should do a straight connection with a target requestURI, i.e

```
client.get(80, "www.google.com", resp -> {});
```

should be equivalent to:

```
client.get(80, "the-proxy", "http://www.google.com", resp -> {}).host("www.google.com:80");
```

so we do have request like:

```
GET http://www.google.com HTTP/1.1
Host: www.google.com
```

while the client connects to `the-proxy` host.

Note: this does not affect `NetClient` that will always continue to create a tunnel using CONNECT

### PR DESCRIPTION
**Pull request by alexlehm**
implement proxy support for http requests
fixes #1498

### CODE REVIEW

**Comment by vietj** [comment]
@alexlehm one commit does not pass the CLA check

**Comment by alexlehm** [comment]
I will rewrite the commits or squash then, not sure why the last commit fails

**Comment by vietj** [comment]
sometimes it happens and we don't know really why...

**Comment by alexlehm** [comment]
ok, changing the last commit didn't work, if will create a new commit

**Comment by alexlehm** [comment]
replaced by #1548

**Pull request closed without merging**
