### PR TITLE
Open ssl session cache enabled pr

### PR DESCRIPTION
**Pull request by ustinovvladi**
Per @vietj request moved the open SSL cache mode setting up to TCPSSLOptions.

See the following thread in the groups: 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/vertx/UUMJ4Y4uMcc

Previous PR:
https://github.com/eclipse/vert.x/pull/1448

### CODE REVIEW

**Comment by ustinovvladi** [comment]
Still problems with CLA... I'm lost :(

**Comment by vietj** [comment]
can you can you squash all your commits into a single one, sign it and make a fresh branch from that ?

**Comment by ustinovvladi** [comment]
How is it going to help? The signing doesn't work

**Comment by vietj** [comment]
as you did merge and several commits, I think the check got confused , it's better to do fresh ones with a single commit, it worked in the past

**Pull request closed without merging**
