### PR TITLE
expose the config after parsing to the Launcher

### PR DESCRIPTION
**Pull request by jtruelove**
Signed-off-by: Jeremy Truelove <jtruelove@gmail.com>

### CODE REVIEW

**Comment by vietj** [comment]
can you review @cescoffier ?

**Comment by vietj** [comment]
can you  explain why you need that @jtruelove ?

**Comment by cescoffier** [comment]
The PR looks good, but I wonder why the callback passing the deployment option cannot be used (`beforeDeployingVerticle`) instead of adding a new hook.

Are you passing in the configuration object Vert.x configuration (and not verticle-centric config) ?

**Comment by jtruelove** [comment]
So here is my use case, I want to use vertx-opentsdb's SPI support and in order to do so I need to make this call happen:

```
// where config here is a value I grab out of the JsonObject that gets created/parsed from the conf.json     //   file passed via the **-conf **flag on the command line 
options.setMetricsOptions(new OpenTsDbOptions(config).setEnabled(true));
```

inside of Launcher's

`void beforeStartingVertx(Vertx vertx);`

So to answer your question, as far as I can see I can't get access to the VertxOptions once it's at the hook `beforeDeployingVerticle` which is too late and VertxOptions have already been used. I could double parse the config file as I have access to the file location via the args coming into Launcher's constructor but that is hacky and dirty which I don't love. So the logical thing seemed to me to provide the config as early in the process as possible in case you need it for doing things in any of the other hooks, and I know you can see the config on deploymentOptions via `getConfig`. I could maybe pass it via another parameter and parse that but I use **-conf** to specify all server config needed for anything which I'm guessing most others do as well, so why split config across files?

**Comment by cescoffier** [comment]
OH I see, thanks for the explanation.

There is a mapping between metrics options and system properties, but I'm not sure it would be convenient for you. 

So, I think adding a callback would make sense in this case. Let me think about it, I will tell you more tomorrow.

**Comment by cescoffier** [comment]
So, I guess the best way is to add the callback and parse the config "early" enough. So, it can be used to configure the `VertxOptions`.

Here is my official +1.

Thanks, and sorry for the delay.

**Comment by jtruelove** [comment]
great! so I guess this will just get merged for the next release?

**Comment by cescoffier** [comment]
Exactly.

**Pull request merged**
