### PR TITLE
small fix to exception logging

### PR DESCRIPTION
**Pull request by kurtostfeld**
Signed-off-by: Kurt Ostfeld <kurt@samba.tv>

### CODE REVIEW

**Comment by vietj** [comment]
can you describe _what_ it fixes ?

**Comment by kurtostfeld** [comment]
The existing log line will do an slf4j `logger.error(exception.toString())`. The new log line should do an slf4j `logger.error("exception", exception)` and if logging is configured accordingly, it will provide full stack trace output, which is what I wanted to see.

**Comment by vietj** [comment]
I believe that you need to configure your logger to see the full stack trace and there is no need to add an artificial "exception" message for this, what is your logger ?

**Comment by kurtostfeld** [comment]
Line 116 here: https://github.com/eclipse/vert.x/blob/master/src/test/java/io/vertx/test/core/SocksProxy.java

is already doing the same thing. Sure, the "exception" string is not useful. The io.vertx.core.logging.Logger class has the `error` method is `error(final Object message, final Throwable t)`; you want to pass the exception as the `Throwable t`, not as the `Object message`. My logging is configured correctly.

**Comment by vietj** [comment]
same as https://github.com/eclipse/vert.x/pull/2277

**Pull request closed without merging**
