### PR TITLE
Update http.adoc

### PR DESCRIPTION
**Pull request by romero**
Fixed some typos.

### CODE REVIEW

**Comment by vietj** [comment]
can you sign your commits and the ECA ?

**Comment by romero** [comment]
Can I do it on github.com?

**Comment by vietj** [comment]
you need to sign ECA on eclipse.org website and sign your commit with "-s" in tool (not sure you can do it on GitHub.com but it may be possible)

**Comment by romero** [comment]
Got it.
Thank you!

**Comment by vietj** [comment]
hi, thanks for the contrib, as it's not code I've commited them directly in master with my account. thanks again

**Comment by romero** [comment]
Oh, cool)
Thank you!

**Pull request closed without merging**
