### PR TITLE
overriding clusterHost and clusterPort on start

### PR DESCRIPTION
**Pull request by zyclonite**
allow overriding cluster host and post in launcher by beforeStartingVertx()

### CODE REVIEW

**Comment by vietj** [comment]
can we get this documented ?

**Comment by vietj** [comment]
first, this PR provides code change and we don't know what are the impact of the changes and what it is useful for. For instance in this commit, I'm giving the motivation/changes so anyone can understand the purpose : https://github.com/eclipse/vert.x/issues/1998

**Comment by tsegismont** [comment]
It's the same here.

The PR has a reference to the original issue (
https://github.com/eclipse/vert.x/issues/2051) which explains the problem.

2017-07-20 9:00 GMT+02:00 Julien Viet <notifications@github.com>:

**Comment by vietj** [comment]
would be good to have a test for this

**Comment by tsegismont** [comment]
@zyclonite would youd mind to add a test in `io.vertx.test.core.LauncherTest` ?

**Comment by zyclonite** [comment]
sure, i will be back in the office next week

**Comment by tsegismont** [comment]
Great! Thanks

2017-07-26 18:26 GMT+02:00 Lukas Prettenthaler <notifications@github.com>:

**Comment by zyclonite** [comment]
i tried to put the test in LauncherTest but i did not find a way to verify if the host and port was set after the launch (no access to options() in ClusteredEventBus) so i put it in RunCommandTest

hope that's fine with you

**Comment by tsegismont** [comment]
What do you mean? You can get  computed options in LauncherTest. Have a
look at:
https://github.com/tsegismont/vert.x/blob/5757213b4ca3d16c9ea8fc76eb913df49aeb4e53/src/test/java/io/vertx/test/core/LauncherTest.java#L478

2017-07-28 14:03 GMT+02:00 Lukas Prettenthaler <notifications@github.com>:

**Comment by zyclonite** [comment]
true but that's what i set "beforeStartingVertx" in a custom launcher... so this would not test if the override worked... and afterStartingVertx does not get me any hint on what host or port was used

in the RunCommandTest i can really test what has been set

**Comment by tsegismont** [comment]
I was thinking of extending `io.vertx.test.core.LauncherTest.MyLauncher` to set cluster options in `io.vertx.test.core.LauncherTest.MyLauncher#beforeStartingVertx` (and call super at the end so that the modified options get stored in `io.vertx.test.core.LauncherTest.MyLauncher#options`)

Then your test would check `io.vertx.test.core.LauncherTest.MyLauncher#options`

**Comment by zyclonite** [comment]
yes, you are right

much cleaner approach, i'll fix that in a minute

**Comment by zyclonite** [comment]
anything missing from my side?

**Comment by tsegismont** [comment]
@zyclonite I just missed the new commit. Looking into the changes right now

**Comment by tsegismont** [comment]
I would have expected a test which verifies a user can override `VertxOptions` cluster host and port in `beforeStartingVertx`. Isn't that what the PR goal? Or did I miss anything?

**Comment by tsegismont** [comment]
Also, could you please add a test to verify that a user can override cluster public host and port as well? Thank you.

**Comment by tsegismont** [comment]
@zyclonite sorry, I misunderstood the tests at first. They're fine.

Let me know if/when you can add a test for cluster public host and port.

**Comment by zyclonite** [comment]
i put it in the existing tests, hope that's ok

**Comment by tsegismont** [comment]
@zyclonite yep that's fine, thank you!

**Comment by tsegismont** [comment]
LGTM

**Comment by vietj** [comment]
I've reverted this PR as it causes the VM to crash during tests, here is the build I get (on OSX)

```
Starting test: LauncherTest#testOverrideClusterHostPortFromProperties 
Starting clustering... 
Metrics has been set to enabled but no VertxMetricsFactory found on classpath 
Failed to start event bus 
java.net.BindException: Can't assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:502)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:487)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

Failed to form cluster 
java.net.BindException: Can't assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:502)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:487)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.689 s
[INFO] Finished at: 2017-09-07T07:22:07+02:00
[INFO] Final Memory: 48M/942M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project vertx-core: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/julien/java/vert.x && /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/bin/java -Xmx1200M -javaagent:/Users/julien/.m2/repository/org/mortbay/jetty/alpn/jetty-alpn-agent/2.0.6/jetty-alpn-agent-2.0.6.jar -jar /Users/julien/java/vert.x/target/surefire/surefirebooter4456391786559270681.jar /Users/julien/java/vert.x/target/surefire/surefire5043830353736750610tmp /Users/julien/java/vert.x/target/surefire/surefire_03603223653651651090tmp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by zyclonite** [comment]
why revert the PR, simply switch the one used bind to the .1 address if osx does not support 127...*

**Comment by vietj** [comment]
@zyclonite I did not diagnostic the issue, as I saw the VM crash I preferred to revert the PR (as we do have other PR to merge). Can you provide a new PR ?

**Comment by zyclonite** [comment]
https://github.com/eclipse/vert.x/pull/2116

**Pull request merged**
