### PR TITLE
Open ssl session cache enabled

### PR DESCRIPTION
**Pull request by ustinovvladi**
Hello, 

As discussed yesterday with @vietj, I exposed  session cache mode setting in HttpServerOptions.
See the following thread in the groups: 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/vertx/UUMJ4Y4uMcc

I did my best to add the new property also to the relevant JUnit tests. I hope you'll find my work suitable. If you have questions/requests - please contact me.

Please pay attention that I'm not committing under the same name/email as in the groups because I was asked by my employer not to use my own email (legal stuff), but I'm the same person.

### CODE REVIEW

**Comment by ustinovvladi** [comment]
I committed using -s:
`git commit -s -m "Exposing session cache mode setting in HttpServerOptions for Open SSL based HTTP servers (see org.apache.tomcat.jni.SSLContext.setSessionCacheMode)"`
What's wrong, why was it not validated. Am I missing something?

**Comment by vietj** [comment]
did you sign the Eclipse CLA ?

**Comment by vietj** [comment]
a comment, the option is added to HttpServerOptions, it would be good to have it rather at the TCPSSLOptions level

**Comment by ustinovvladi** [comment]
Ok, I'll look into it

**Comment by ustinovvladi** [comment]
TCPSSLOptions is a base class for EventBus, HttpClient and NetClient options. However the ssl session mode exists only in Netty's OpenSslServerSessionContext.java, which means - not relevant for client side and/or event bus. Correct me if I'm wrong here.

**Comment by ustinovvladi** [comment]
And yes, I've signed the Eclipse CLA

**Comment by vietj** [comment]
you can use OpenSSL for event bus SSL or just plain TCP if you like

**Comment by vietj** [comment]
for the CLA can you redo a clean branch ?

**Comment by ustinovvladi** [comment]
Ok, I will try

**Pull request closed without merging**
