### PR TITLE
Update package-info.java

### PR DESCRIPTION
**Pull request by romero**
Fixed some typo

### CODE REVIEW

**Comment by vietj** [comment]
hi, now we have moved the docs here https://github.com/eclipse/vert.x/blob/master/src/main/asciidoc/http.adoc (the current file you edited is a left-over we need to clean up), can you reopen a new IP valid PR please ?

**Comment by romero** [comment]
Sure, thank you!

**Comment by romero** [comment]
-- can you reopen a new IP valid PR please ?

What should I do for it?

**Comment by vietj** [comment]
you need to sign the ECA (Eclipse Contributor Agreement) : https://github.com/vert-x3/wiki/wiki/How-to-contribute-to-Vert.x

**Comment by romero** [comment]
Hm.
Already done it.

**Pull request closed without merging**
