### PR TITLE
wip #2230 refactor buffer Http1xServerConnection 

### PR DESCRIPTION
**Pull request by st-h**
as discussed in #2230 this PR splits the single queue from Http1xServerConnection into two separate
queues. I tried to move stuff that belongs to the Request or the Response into the appropriate places, but it turned out to be difficult within the current structure to separate concerns clearly. 
There are still some things which could probably be cleaned up, but I wanted to submit this by now as I am unsure if splitting the queues really reduces complexity. And I am not 100% sure if the vertx context related stuff makes sense.

### CODE REVIEW

**Comment by vietj** [comment]
Actually  I do have code for that and I would like rather for 3.6 (I can push the code I have).

**Comment by vietj** [comment]
please see this commit https://github.com/vietj/vert.x/commit/19f60b8b1fe06c450c4e03fd9ab0df43244637a0

**Comment by vietj** [comment]
the main motivation for this refactor (look at the previous commit) is to have an improvements of `ReadStream` so when it is _paused_, a new `read` method can read a requested number of items from the stream.

The implementation of this is the `EventQueue` that allows to _push_ items in the queue and have the `ReadStream` delegate the item management to the queue. Without this `HttpServerRequestImpl ` using it is very difficult.

The main overall purpose of this change are:

- simplify the implementation of Reactive-Streams from `ReadStream` (so basically a `ReadStream` in paused mode behave like a unicast publisher) : the code in vertx-reactive-streams, vertx-rx-java and vertx-rx-java2 would be simplified and possibly simpler (merging the implicit `ReadStream` queue + the adapter queue into a single queue)
- provide a base class for implementing `ReadStream` (`EventQueueBase`) that basically is a queue with an `handle` method

**Comment by vietj** [comment]
and that would be for 3.6 I think - for now I'm just trying to implement in vertx-core for a few important cases such as http server, async file, then try to see how it can be used in vertx-rxjava2 and reactive-streams.

**Comment by st-h** [comment]
> Actually I do have code for that and I would like rather for 3.6

Well, that must have been quite a misunderstanding. Feel free to close this then.

**Comment by vietj** [comment]
n/p :-) , I t hin that before 3.6 we will ahve to check it still works with vertx-mongo-streams

**Comment by vietj** [comment]
thanks for the time spent

**Pull request closed without merging**
