### PR TITLE
Enable websocket compression

### PR DESCRIPTION
**Pull request by disparlure**
Enable compression for websockets. Server and client side support included. Continuation of the work done in #2045 .

### CODE REVIEW

**Comment by CodingFabian** [comment]
@disparlure the easiest way to get around the individual commits would be to just combine all your changes into a single commit like this:
https://stackoverflow.com/questions/17354353/git-squash-all-commits-in-branch-without-conflicting

**Comment by disparlure** [comment]
Tried the suggested process, it does not seem to have worked as intended.

**Comment by CodingFabian** [comment]
tried to help you out in #2165 - I have squashed all the changes for you into a single commit signed by us both.

**Comment by disparlure** [comment]
Assuming we're closing this in favor of https://github.com/eclipse/vert.x/pull/2165.

**Pull request closed without merging**
