### PR TITLE
More cluster tests

### PR DESCRIPTION
**Pull request by tsegismont**
- put with ttl
- putIfAbsent with ttl
- lock is released when owning node goes down

### CODE REVIEW

**Comment by cescoffier** [comment]
👍

**Comment by vietj** [comment]
do we need also to have PR in cluster managers to handle correctly these tests ? cc @stream1984 @cescoffier @agura

**Comment by agura** [comment]
> do we need also to have PR in cluster managers to handle correctly these tests ?

@vietj I think we don't. Tests should be handled automatically because cluster manager specific test classes just extend modified test classes.

**Comment by tsegismont** [comment]
I have sent a PR to the Hazelcast repo
https://github.com/vert-x3/vertx-hazelcast/pull/44

Note that the new lock tests are *ignored* by default (because they can't
pass with the fake cluster manager)

I am going to test Ignite and Zookeeper implementations.



2016-09-23 16:03 GMT+02:00 Andrey Gura <notifications@github.com>:

**Comment by cescoffier** [comment]
We should add a wiki page about cluster manager implementation to explain which tests they must pass and how to enable them.

**Comment by tsegismont** [comment]
For Ignite CM, see vert-x3/vertx-ignite#22 and vert-x3/vertx-ignite#23

**Comment by tsegismont** [comment]
For Zookeeper CM, see vert-x3/vertx-zookeeper#32 and vert-x3/vertx-zookeeper#33

**Comment by tsegismont** [comment]
For JGroups CM, see vert-x3/vertx-jgroups#28

**Comment by tsegismont** [comment]
@vietj updated or filed issues for all CMs in the stack

**Comment by vietj** [comment]
should I merge for core and then you merge the others ?

**Comment by stream1984** [comment]
I would fix these bug when core merged this PR

**Comment by tsegismont** [comment]
Julien, yes please merge this one. I'll check with Stream and Andrey for ZK
and Ignite.

2016-09-27 6:36 GMT+02:00 Stream <notifications@github.com>:

**Comment by agura** [comment]
vert-x3/vertx-ignite#22 fixed. With #23 there are some problems. In progress.

**Pull request merged**
