### PR TITLE
Log the error when client isn't able to connect to remote host.

### PR DESCRIPTION
**Pull request by manish-panwar**
https://groups.google.com/forum/#!searchin/vertx/log$20the$20error/vertx/fwZNJDR6IFI/Va_GTtZ0BAAJ 

We are using a cluster of 2 nodes and intentionally blocked the port 41232 (we are using a dedicated port for Vertx communication). Since port is blocked, we get connection timeout error and "else" condition in given below code is executed.

### CODE REVIEW

**Comment by manish-panwar** [comment]
Hey guys,

Even though I have added "Signed-off" but it's not passing  IP validation. I always have issues with this process. Can you guys accept this pull request since change is so trivial?

**Comment by alexlehm** [comment]
@manish-panwar I think you have to sign the eclipse CLA with the same email you are using for git to get the check passing

**Comment by jan-zajic** [comment]
@manish-panwar, i made similiar fix #1562, didn't known about your pull request ;). I have Checks for CLA Ok, so someone can merge my change, or if @alexlehm going to merge this PR, please let me know and i close other one. I personaly don't care who fix it, but it's very important to log that exceptions (
in my humble opinion).

**Comment by manish-panwar** [comment]
Thanks a lot, @jan-zajic  !!!

**Comment by manish-panwar** [comment]
@jan-zajic : @vietj Already added your PR  with review label. I am sure he will review it soon and merge it.

**Comment by alexlehm** [comment]
@manish-panwar I believe the review label comes from the waffle.io tool, you might want to ask on the google group (I believe he's on vacation this week)

**Comment by manish-panwar** [comment]
Being handled part of https://github.com/eclipse/vert.x/pull/1562, so closing this PR.

**Pull request closed without merging**
