### PR TITLE
spelling post -> port

### PR DESCRIPTION
**Pull request by Sammers21**

### CODE REVIEW

**Comment by Sammers21** [comment]
Can someone suggest what is wrong in my commit?

**Comment by vietj** [comment]
you should make one clean PR with a single commit that is sign-off

**Comment by ruslansennov** [comment]
You should sign CLA.
https://www.eclipse.org/legal/CoO.php (see "sign" link)

**Comment by Sammers21** [comment]
@ruslansennov, I have signed ECA and all my commits made is "-s" flag, but still.... it doesn't work

**Comment by Sammers21** [comment]
@ruslansennov image

**Comment by ruslansennov** [comment]
ok, then it seems @vietj is right: you should make one clean PR with a single commit that is sign-off

**Comment by Sammers21** [comment]
@vietj and you @ruslansennov  are right. I will create new RP with a single commit, but I m need to be sure that my commit will be valid and pass all checks successfully. Now it does no happen.

**Comment by Sammers21** [comment]
The question is why my commit don't pass all checks? So commit is signed 
image

**Comment by Sammers21** [comment]
All checks are passed

**Comment by tsegismont** [comment]
@Sammers21 thank you!

**Pull request merged**
