### PR TITLE
Add #getUnsignedXXX methods to Buffer class

### PR DESCRIPTION
**Pull request by tsegismont**
Helpful methods for decoding bandwith-optimized network protocols.

Signed-off-by: Thomas Segismont <tsegismont@gmail.com>

### CODE REVIEW

**Comment by tsegismont** [comment]
I already had an Eclipse account and I thought my CLA was still valid. But it looks like they invalidate it after some time... I've signed it again. Not sure what can trigger a new CLA validation process.

**Comment by tsegismont** [comment]
I've changed the commit comment and pushed again. The Eclipse CLA hook is happy now.

**Comment by vietj** [comment]
it looks good, however shouldn't we have _setUnsignedXXX_ / _appendUnsignedXXX_ / as well ?

**Comment by tsegismont** [comment]
You don't need setUnsignedXXX / appendUnsignedXXX , you can cast to the desired type. For example to write an unsigned short stored in an `int` named `unsignedShort`:
```java
buffer.setShort(pos, (short) unsignedShort);
```

**Comment by tsegismont** [comment]
If you take a look at Netty's ByteBuff API, there are no such methods. If you prefer, I can add them in Vertx's Buffer API. Example:

```java
  public Buffer setUnsignedShort(int pos, int s) {
    ensureWritable(pos, 2);
    buffer.setShort(pos, (short) s);
    return this;
  }
```

**Comment by vietj** [comment]
casting will not work in other languages than Java or Groovy (i.e JS or Ruby, etc...)

**Comment by tsegismont** [comment]
And would that work with methods following the example above?

**Comment by vietj** [comment]
I think yes

**Comment by tsegismont** [comment]
Done

2015-07-02 13:30 GMT+02:00 Julien Viet <notifications@github.com>:

**Comment by vietj** [comment]
looks good to me. will merge it.

**Comment by vietj** [comment]
can you sign the second commit for append/set please ?

**Comment by tsegismont** [comment]
Ha ... I forgot that. I'll squash the commits, sign the resulting one and
ping you when ready.

**Comment by tsegismont** [comment]
@vietj done

**Comment by purplefox** [comment]
Is this ready to merge julien? @vietj

**Comment by vietj** [comment]
no it's not.

**Comment by vietj** [comment]
yes it's fine to merge :-)

**Comment by vietj** [comment]
I misread and thought you asked if it was merge already, my bad :-) it can be merged now

**Comment by purplefox** [comment]
I've just noticed - there are no docs for the new functionality.

Could you add something in package-info.java for this?

**Comment by tsegismont** [comment]
Just sent another PR:
https://github.com/eclipse/vert.x/pull/1103/files

Cheers

2015-07-08 9:57 GMT+02:00 Tim Fox <notifications@github.com>:

**Pull request merged**
