### PR TITLE
Rebase PR #1276 on http2-openssl

### PR DESCRIPTION
**Pull request by dan-lind**
Rebased PR #1276 onto http2-openssl as suggested by @vietj. Had to rewrite some of the tests because of the refactoring on this branch. Thus the ignored test mentioned in PR #1276 is no longer part of this PR.

### CODE REVIEW

**Comment by dan-lind** [comment]
@vietj Didn't help this time :-( Any suggestion on who I should reach out to?

**Comment by dan-lind** [comment]
It looks to me like the issue might be that I'm trying to push two commits, and one of them (davidsilvas) was not authored by me.

**Comment by vietj** [comment]
just squash the commits and author it.

**Comment by dan-lind** [comment]
Finally, there we go :-)

**Comment by vietj** [comment]
thanks!

**Pull request merged**
