### PR TITLE
fix to completer impl to actually fail the Future

### PR DESCRIPTION
**Pull request by joydip**

### CODE REVIEW

**Comment by vietj** [comment]
ouch... can you provide a test case too please ?

**Comment by vietj** [comment]
fortunately this default implementation is overriden by CompositeFuture and FutureImpl in Vert.x Core. However it may be not in other modules.

**Comment by joydip** [comment]
Sure, I will work on adding a test case for this

**Comment by vietj** [comment]
hi @joydip any news from the tests ?

**Comment by joydip** [comment]
@vietj sorry have been busy but I'll work on the tests today and update the PR

**Comment by joydip** [comment]
@vietj added test

**Comment by vietj** [comment]
thanks, can you sign-off the commit with the added test please ?

**Comment by joydip** [comment]
oops, sorry, added a signoff on the commit with the test.

**Comment by vietj** [comment]
thanks

**Pull request merged**
