### PR TITLE
Some improvements to net param defaulting and use different eventloop…

### PR DESCRIPTION
**Pull request by purplefox**
… for acceptor for faster connection setup under load

### CODE REVIEW

**Comment by cescoffier** [comment]
Ok for me.

**Comment by vietj** [comment]
looks good

**Comment by vietj** [comment]
should we expose also this acceptor event loop in Vert.x as we do expose the eventLoopGroup under nettyEventLoopGroup ?

**Comment by purplefox** [comment]
This is more of an internal thing, we don't really want to expose it.

**Comment by vietj** [comment]
ok

**Pull request merged**
