### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by srueg**
- Fix the index for the `addArgument` example
- Fix typo as to has

### CODE REVIEW

**Comment by tsegismont** [comment]
Can you amend your commit to sign it off?

**Comment by srueg** [comment]
I did, but somehow it doesn't accept it...

**Comment by tsegismont** [comment]
Signed or signed-off? I mean, did you use `git commit -s` ?

**Comment by tsegismont** [comment]
Also, you sign the Eclipse CLA

**Comment by srueg** [comment]
Sorry, my bad. Now it looks better

**Comment by tsegismont** [comment]
Thank you. I just realized that you modified the generated doc file. The file you need to update is `vert.x/src/main/java/io/vertx/core/cli/annotations/package-info.java`, plus the corresponding example method.

Please read https://github.com/vert-x3/wiki/wiki/How-is-managed-vert.x-documentation if you want to know more about the process.
In particular, after changing the source file, please rebuild the project to regenerate doc files, and include the changes in the commit.

Thank you for contributing!

**Comment by srueg** [comment]
Next try 😃 
Thank you for your patience, it's my first time contributing to an open source project...

**Comment by tsegismont** [comment]
LGTM. Thanks @srueg !

**Pull request merged**
