### PR TITLE
Doc fixes typos grammar

### PR DESCRIPTION
**Pull request by FreedomBen**

### CODE REVIEW

**Comment by FreedomBen** [comment]
Oh no!  Same issue.  I'm sorry this is being such a pain.   I wonder is it checking the public facing email address for my github account instead of or as well as the one I used in the commit message?

**Comment by FreedomBen** [comment]
I just changed my email settings to expose my email address (we'll see how bad it gets spammed, sadlol).

**Comment by FreedomBen** [comment]
btw @vietj , this is most certainly not the appropriate forum to say this and for that I apologize, but thanks for being responsive on this project.  Also I see you work at Red Hat, and I'm a huge RH fan boy, so you're already endeared to me :-)

**Comment by vietj** [comment]
this PR is not valid as well

**Comment by FreedomBen** [comment]
Is there a way to re-run the ip-validation now that I've exposed my real email address on my public profile?  I don't see any controls on my end.  I could probably push a dummy commit to the branch but I'd hate to clutter the PR

**Comment by vietj** [comment]
@tsegismont told me that a push --force on the PR should work

**Comment by FreedomBen** [comment]
I did a force push but I don't know if the check re-ran or not.  Is the source code of the ip-validation public?

**Comment by vietj** [comment]
make a new PR 😂

**Comment by FreedomBen** [comment]
Haha, cool will do

**Pull request closed without merging**
