### PR TITLE
DnsClient: no option to enable the netty logger - fixes #2445

### LINKED ISSUE #2445: DnsClient: There is no option to enable the netty logger

### PR DESCRIPTION
**Pull request by stephanebastian**
Signed-off-by: Stephane Bastian <stephane.bastian.dev@gmail.com>

### CODE REVIEW

**Comment by vietj** [comment]
for testing logging can you reuse what is in HttpTest testLogging() and make testLogging accept a Runnable ?

**Comment by vietj** [comment]
and move testLogging to TestUtils

**Comment by vietj** [comment]
can you also use the new TestUtils method in other places like DatagramTest, HttpTest and NetTest ?

**Comment by stephanebastian** [comment]
Sure. However I was planning on submitting a different PR to update all test classes that should now be using the new method in TestUtils. So this PR is only related to the DnsClient. But I as you prefer, let me know

**Comment by vietj** [comment]
let's do everything in this pr, it's fine and atomic :-)

**Comment by stephanebastian** [comment]
@vietj no problemo :) updated the PR, all tests are green

**Pull request merged**
