### PR TITLE
Implement a log delegate using Log4J 2.

### PR DESCRIPTION
**Pull request by cescoffier**
This is related to https://github.com/vert-x3/issues/issues/64

* Add log4j 2 dependencies
* Implement the delegate and the factory
* Implement tests
* Update documentation

### CODE REVIEW

**Comment by cescoffier** [comment]
@vietj @pmlopes ready for review

@vietj it adds two 'provided' dependencies - not sure if we need to open CQ for these.

**Comment by vietj** [comment]
yes we should...

**Comment by pmlopes** [comment]
:+1:

**Comment by vietj** [comment]
this branch does not pass anymore (due to change in Recording that does not record anymore the System.out but the JUL logger)

**Pull request merged**
