### PR TITLE
Implement Temporal Support for JSON

### PR DESCRIPTION
**Pull request by pmlopes**
Signed-off-by: Paulo Lopes <paulo@mlopes.net>

This completes the implementation of I-JSON

### CODE REVIEW

**Comment by purplefox** [comment]
Would it be a good idea to allow instants to be added/retrieved as longs too?

In many cases, Java programs handle date/times as longs and forcing a conversion to Instant just so it can be converted to String seems a bit long-winded.

**Comment by purplefox** [comment]
Maybe that's just a a suggestion for the future. What you have here looks good.

**Comment by pmlopes** [comment]
long timestamps are not part of the RFC, the RFC defines temporal -> String only, the String -> Instant is added for convenience.

The issue with timestamps is that languages like javascript have no long int type which may cause longs to be truncated, although the json spec does allow any precision.

Acording to ES6 (EcmaScript2015):

```
Number.MAX_SAFE_INTEGER // 9007199254740991
Math.pow(2, 53) - 1     // 9007199254740991
```

It will for sure handle all the current dates but if someone is making a forecast app that uses only far future dates we are still missing the last 10 bits of the long range...

For users only caring about longs then the current API should be enough, for example:

I can put a timestamp as long:
```
obj.put("myTimestamp", System.currentTimeMillis());
```
and later read it to an instant like:
```
Instant instant = Instant.ofEpochMilli(obj.getLong("myTimestamp"));
```

**Comment by purplefox** [comment]
I didn't mean storing the long as a value in the json object but just an ability to set it with a long.

long now = System.currentTimeMillis();
obj.putTemporal("somekey", now);

such that the long is stored as a temporal internally.

with your changes I have to convert it to an Instant first which is an extra step.

**Pull request merged**
