### PR TITLE
Use inflight DNS client instead

### PR DESCRIPTION
**Pull request by testn**
I noticed a similar problem as @luengnat with the DNS vert.x client which did not use inflight dns resolver and caused too much load on our DNS server. So I cook up a patch that should address the issue

### CODE REVIEW

**Comment by vietj** [comment]
can you give a thorough explanation of the issues you encountered and how this change solves it ?

**Comment by testn** [comment]
When there is a request to resolve a host, it will consult with the local DNS cache first. If the entry does not exist in the cache, it will make a request. Everything seems well. However, when another request is made while the other DNS request is in flight, it will send out another DNS request. This means that if there are a lot of requests being made to a server while the DNS entry is not cached yet, it will send multiple requests to the DNS server. A lot of DNS server implementation, in our case, DNS BIND, have a rate limiting feature where it refuses to serve some requests when there are too many identical requests coming from the same ip address.

**Comment by vietj** [comment]
ok great, thanks!

**Comment by luengnat** [comment]
+1. Thank you very much for providing the PR

**Comment by vietj** [comment]
did you run the testsuite with this change ?

**Comment by testn** [comment]
yes but let me re-run it against the rebased code

**Comment by vietj** [comment]
any news from taht ?

**Comment by testn** [comment]
all green!

**Pull request merged**
