### PR TITLE
Removed deprecated Netty code

### PR DESCRIPTION
**Pull request by tsegismont**
Some tests had to be updated because of:
- HTTP with Strings over a TCPServer
- Case sensitive header map

### CODE REVIEW

**Comment by vietj** [comment]
as this has an impact on performance, can you make sure that the new changes are equivalent to the existing usage of ascii strings ?

**Comment by tsegismont** [comment]
1/ I haven't checked if there's a perf impact, but I don't believe there
would be: the deprecated methods simply call the new methods.

2/ We are using AsciiString already, as
io.netty.handler.codec.http.HttpHeaders.newEntity
actually creates an AsciiString.
The difference is that with this PR, we don't create our own constants but
reuse those of Netty, which are defined with lower case letters.
The potential impact is for code doing manual http parsing, like some of
our tests do (see the changes).

2017-04-10 9:37 GMT+02:00 Julien Viet <notifications@github.com>:

**Comment by vietj** [comment]
I would rather keep the existing behavior concerning the constant case and not change it

**Comment by tsegismont** [comment]
Let me elaborate on point 2/

We already use AsciiString, created with HttpHeaders.newEntity. The
parameter provided to newEntity is a deprecated Netty constant, defined
with a mix of upper and lower case letters (e.g. "Content-Type")
With this PR, we also use Netty constants, but they have changed the values
to all lower case (e.g. "content-type")

If we want to keep the constant case, we need to either go back to the
deprecated constants or create our own. The former makes no sense since
it's the purpose of the PR to get rid of the deprecated code.
I'm not opposed to the latter but why do this since the spec makes it clear
the HTTP header names are case-insensitive?


2017-04-11 10:07 GMT+02:00 Julien Viet <notifications@github.com>:

**Comment by tsegismont** [comment]
@vietj have you seen the previous comment?

**Comment by vietj** [comment]
@tsegismont my point is that I'm doing performance test at the moment, and I would like to validate it by doing actual benchmarks

**Comment by tsegismont** [comment]
@vietj ping

**Comment by vietj** [comment]
let me test it :-)

**Comment by tsegismont** [comment]
@vietj rebased on master (had conflicts since your perf PR was merged)

**Comment by vietj** [comment]
I would like to benchmark it before merging it to see if the change of constant has an impact (it might have)

**Comment by tsegismont** [comment]
I will open another PR: rebasing on master will be harder than starting from scratch. Also, I'll split the work into 2 PRs as discussed with @vietj :

1. deprecated code replacement 
2. http headers change

We'll test 2/ in the perf lab

**Pull request closed without merging**
