### PR TITLE
Ssl cert refactoring

### PR DESCRIPTION
**Pull request by dachaac**
Updates instructions on how to create certificates and keys for testing.

Changes expiration date for certificates to be 10 years as existing certificates were already expired.

Changes CA names to be more descriptive.

Changes client certificate to be named as "client" to differentiate it from DNS based certificate names.

Removed the need to use external tools (apart from keytool and openssl) when recreating certs.

### CODE REVIEW

**Comment by dachaac** [comment]
Used following helper script to auto-create certs:
```
echo "set -xe" > recreate-ssl.sh
echo "rm -rf root-ca int-ca other-ca | true" >> recreate-ssl.sh
echo "rm *.p12 *.jks *.pem *.crt *.key | true" >> recreate-ssl.sh
cat ssl.txt | grep -v -e ^# | grep -v -e ^[1-5T\(] | grep -v -e ^\- >> recreate-ssl.sh
```

**Comment by dachaac** [comment]
Tried to verify that all tests pass like before.

There are changes to output but seems to be because certs were previously expired.

**Comment by vietj** [comment]
so keyeplorer is not needed anymore ?

**Comment by vietj** [comment]
thanks @dachaac !

**Pull request merged**
