### PR TITLE
Default redirect handler: do not fail on URIs without explicit port

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes java.lang.IllegalArgumentException: port out of range:-1

### CODE REVIEW

**Comment by vietj** [comment]
can you explain how to reproduce it so we can add tests ?

**Comment by vietj** [comment]
I see, hard to have a test for it as it uses port 80 or 443 ...

**Comment by vietj** [comment]
I'm going to extract the code in a static method and test this method instead

**Comment by tsegismont** [comment]
Exactly

2017-03-01 23:17 GMT+01:00 Julien Viet <notifications@github.com>:

**Pull request merged**
