### PR TITLE
Updated libraries versions

### PR DESCRIPTION
**Pull request by fmatar**

### CODE REVIEW

**Comment by fmatar** [comment]
@vietj I can update the version to 6 the build runs smoothly with those libraries, however I can revert the netty version to 4.0.25. Would that work?

**Comment by purplefox** [comment]
Hmm, we should really be using the latest Netty for the 3.0 release!

**Comment by purplefox** [comment]
The versions we submit to Eclipse should be the latest ones. Netty 4.0.25 is about 6 months old

**Comment by vietj** [comment]
ok, but we haven't tested the 4.0.28 version, and we have been running fine with 4.0.25. We can update to 4.0.28 but that will impact the process. Let me know.

**Comment by purplefox** [comment]
I've just updated it and the test suite seems ok. We can't release V3 with a 6 month old Netty version

**Comment by normanmaurer** [comment]
@purplefox @vietj FYI I will release 4.0.29.Final most likely end of the week.

**Comment by vietj** [comment]
@normanmaurer good to know
@purplefox no problem, I will file an Eclipse CQ with this update

**Comment by purplefox** [comment]
@normanmaurer I bet you're glad you don't have to deal with Eclipse process rules any more ;)

**Comment by normanmaurer** [comment]
@purplefox I have other rules to follow ;)

**Pull request closed without merging**
