### PR TITLE
Replace Apex with Web

### PR DESCRIPTION
**Pull request by pmlopes**
Signed-off-by: Paulo Lopes <paulo@mlopes.net>

### CODE REVIEW

**Comment by pmlopes** [comment]
@purplefox @vietj @cescoffier please merge

**Comment by purplefox** [comment]
Stuff like this you can just commit directly in master

**Comment by pmlopes** [comment]
i don't have push rights ;)

**Comment by purplefox** [comment]
ah ok, sorry this is eclipse vert.x

**Pull request merged**
