### PR TITLE
Fixed SLF4JLogDelegateTest on windows platform due to CR/LF inconsistency

### PR DESCRIPTION
**Pull request by Mart-Bogdan**
Logger tests was failing on windows platform. Error with line end characters.

### CODE REVIEW

**Comment by vietj** [comment]
Can you capture the system.lineSeparator in a constant in the test class and reuse it ?

**Comment by Mart-Bogdan** [comment]
ok, I'll update PR

**Comment by Mart-Bogdan** [comment]
Updated the code

**Comment by Mart-Bogdan** [comment]
This issue was fixed with #1345 patch, by @cescoffier's commit 67c7a007222adc2f4919719c161cfaf3dcaf46f5

So, Julien, what do you think, removing **\n** at all, and using contains is better solution for problem?

**Pull request closed without merging**
