### PR TITLE
Fix message producer

### PR DESCRIPTION
**Pull request by amannocci**
Motivation:
We forget to add credit header in MessageProducer when we set it with deliveryOptions.
As a result the drain handler will never be call.

Modification:
Add credit header when we set delivery options.

Result:
The drain handler will be call in every situation.

Signed-off-by: amannocci adrien.mannocci@gmail.com

### CODE REVIEW

**Comment by vietj** [comment]
@amannocci can you sign the Eclipse CLA and your commit ? see https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md

**Comment by amannocci** [comment]
I have signed the Eclipse CLA but I don't understand what goes wrong here ?

**Comment by vietj** [comment]
did you sign the CLA after doing the PR ? can you try a new one ?

**Comment by amannocci** [comment]
I have signed the Eclipse CLA before the PR  and my two commits.
In the first one I forgot to Sign-Off.

**Comment by vietj** [comment]
can you provide an updated PR ?

**Pull request closed without merging**
