### PR TITLE
Avoid accessor method for `OrderedExecutorFactory::log`

### PR DESCRIPTION
**Pull request by circlespainter**
The accessor method is not an issue per-se but it causes the Quasar Java agent in the forthcoming release, when used, to print an harmless but annoying error at vert.x boot:

```
ERROR: Unable to instrument class io/vertx/core/impl/OrderedExecutorFactory$OrderedExecutor co.paralleluniverse.fibers.instrument.UnableToInstrumentException: Unable to instrument io/vertx/core/impl/OrderedExecutorFactory$OrderedExecutor#lambda$new$261()V because of synchronization
```

(See https://github.com/puniverse/quasar/issues/160#issuecomment-205977756 and following for details)

An easy workaround for the user is to run the agent with the `=m` suffix ("allow monitors").

### CODE REVIEW

**Comment by vietj** [comment]
@circlespainter you need to sign the Eclipse CLA and sign-off your commit

**Comment by circlespainter** [comment]
Sorry, it should be OK now.

**Comment by vietj** [comment]
can you add a comment on the package protected modifier that it is important for quasar ?

**Comment by circlespainter** [comment]
Done.

**Pull request merged**
