### PR TITLE
Rebase PR #1276 on http2-openssl

### PR DESCRIPTION
**Pull request by dan-lind**
Rebased PR #1276 onto http2-openssl as suggested by @vietj. Had to rewrite some of the tests because of the refactoring on this branch. Thus the ignored test mentioned in PR #1276 is no longer part of this PR. This PR replaces #1365 where I had some ip-validation issues.

### CODE REVIEW

**Comment by vietj** [comment]
this one seems to pass validation :-)

**Comment by dan-lind** [comment]
I was unsure as the PR is missing the "to_review" tag and there is no green success check saying "All checks have passed".

**Comment by vietj** [comment]
it seems to miss documentation + example like there is for enabledCipherSuite .

**Comment by dan-lind** [comment]
I have now updated the PR with documentation and example, but now once again the ip-validation is failing, and I honestly have now clue why.

**Comment by vietj** [comment]
I have no clue either :-(

**Comment by dan-lind** [comment]
I'll try to create yet another PR since that solved the validation issue last time :-/

**Pull request closed without merging**
