### PR TITLE
Use Netty's HTTP header constants

### PR DESCRIPTION
**Pull request by tsegismont**
...instead of keeping our own with uppercase letters (not HTTP/2 friendly)

### CODE REVIEW

**Comment by tsegismont** [comment]
@vietj this is the separate PR you wanted we test in the perf lab

**Comment by tsegismont** [comment]
Verified the pull request in the perf lab and it does not impact benchmark results

**Comment by tsegismont** [comment]
Do not merge yet, the PR branch is based off of #2509 branch

**Comment by tsegismont** [comment]
@vietj can you take a look? Just rebased the branch off of master (#2509 now merged)

**Comment by vietj** [comment]
sure will do

**Comment by vietj** [comment]
@luengnat this is part of a 2 steps modifications and Thomas did the first one for the moment

**Pull request merged**
