### PR TITLE
spelling post -> port

### PR DESCRIPTION
**Pull request by Sammers21**

### CODE REVIEW

**Comment by tsegismont** [comment]
Thank you  @Sammers21 ! Have you signed the Eclipse CLA?

**Comment by Sammers21** [comment]
@tsegismont no, I haven't. How could I do that?

**Comment by Sammers21** [comment]
@tsegismont , i have a problem with signed commits. so checks have failed because of first 2 commits without a signature? Do i have to create new PR?

**Comment by Sammers21** [comment]
So, I m understand how to do right commit. I gonna to create new PR and close this one

**Comment by tsegismont** [comment]
Just saw your message. You could have rebased your branch on master, edited
the commits to add the -s flag and forced pushed.

This worked for me in the past.



2017-05-22 12:25 GMT+02:00 Pavel Drankov <notifications@github.com>:

**Pull request closed without merging**
