### PR TITLE
Fixes time unit in doc

### PR DESCRIPTION
**Pull request by EmadAlblueshi**

### CODE REVIEW

**Comment by EmadAlblueshi** [comment]
@vietj I don't know what is wrong!!!

**Comment by EmadAlblueshi** [comment]
@vietj did I miss something?

**Comment by vietj** [comment]
@EmadAlblueshi you need to sign the Eclipse ECA and sign-off your commit

**Comment by EmadAlblueshi** [comment]
Hi, @vietj I did sign to [Eclipse ECA](https://www.eclipse.org/contribute/cla) with sign-off commit 

`
git commit -s -m "Fixes time unit in doc"
`

Unfortunately, it did not work!

**Comment by vietj** [comment]
can you try a new PR with just a single commit ? I see many branch merges and perhaps they confuse the CLA checker

**Comment by EmadAlblueshi** [comment]
@vietj Ok

**Comment by EmadAlblueshi** [comment]
@vietj It works now https://github.com/eclipse/vert.x/pull/1696 as you said many branch merges confuse the CLA checker

**Pull request closed without merging**
