### PR TITLE
Future recovering methods

### PR DESCRIPTION
**Pull request by ruslansennov**
I believe these are very useful methods (at least for me)

### CODE REVIEW

**Comment by vietj** [comment]
that seems related a bit to circuit breaker

**Comment by ruslansennov** [comment]
> that seems related a bit to circuit breaker

Just another two FP methods, additional to `compose()` and `map()`

**Comment by vietj** [comment]
I would only keep `recover` with a Future and people recovering with a constant, would do 'recover(err -> Future.succeeded(foo))'

**Comment by ruslansennov** [comment]
makes sense, thank you
PR updated

**Comment by vietj** [comment]
nice reactivity :-)

**Comment by vietj** [comment]
a test for the case the mapper function fails is missing

**Comment by ruslansennov** [comment]
done

**Comment by vietj** [comment]
last thing, I think we need in the documentation of recover, mention that if the mapper fails, then the returned future will be failed with this failure.

**Comment by ruslansennov** [comment]
done!

**Comment by vietj** [comment]
thanks for the contribution @ruslansennov

**Comment by ruslansennov** [comment]
@vietj 
```
Could not generate model for mapper: Illegal type ? super java.lang.Throwable of kind WILDCARD
  default Future<T> recover(Function<? super Throwable, Future<T>> mapper) {
```

Sorry, I've tested this PR by run `FutureTest` only

**Comment by vietj** [comment]
@ruslansennov actually I do have some concerns about this patch.

As the `map` method, it would be good to have a similar method in `AsyncResult<T>`. However `recover` uses a function that returns a `Future<T>` (like compose).

You propose `recover` and `recoverWith` and I think it would be good to have `recoverWith` that can go in `AsyncResult`.

However I'm not fan of `recoverWith` name. If you think of how to name such method in a better way similar to:

- compose / map
- recover / ???
- ??? / recover

for instance RxJava uses:
- onErrorResumeNext
- onErrorReturn

**Comment by vietj** [comment]
maybe `orElse` ?

```
void foo(ar -> {
  ar.orElse(err -> "something");
});
```

```
fut.orElse(err -> "something");
```

that could be overloaded with a constant like `map`

```
ar.orElse("constant");
```

```
fut.orElse("constant");
```

**Comment by vietj** [comment]
Actually it seems like a good fit to me.

**Comment by ruslansennov** [comment]
@vietj this patch inspired by [similar methods in Javaslang](https://github.com/javaslang/javaslang/blob/44a6887e34037566fca4964ccc91d5d97aab422c/javaslang/src/main/java/javaslang/concurrent/Future.java#L791) which follow [similar methods in Scala](https://github.com/scala/scala/blob/bff11b611ae4c9a02c456847fbbb4695bc3f40ec/src/library/scala/concurrent/Future.scala#L389). Also I like `onErrorResumeNext`/`onErrorReturn` names. But `orElse` sounds a bit confusing in this case

**Comment by vietj** [comment]
@ruslansennov yes, I see your point of view and this is more inspired from https://github.com/advantageous/reakt and `Optional` than from a functional library.

**Comment by vietj** [comment]
I believe it's a good fit because we have compose/map and map can accept a `Function<T, Value>` or just a value, the recovering method counterpart should accept both and in this case the `orElse(Value)` is exactly what we want here

**Comment by vietj** [comment]
in javaslang that would be `javaslang.control.Option` that provides an `orElse`.

Given that in Vert.x `Future<T>` extends `AsyncResult<T>` that seems ok to me.

**Comment by vietj** [comment]
btw in Vert.x future, the `compose` is the classic `flatMap` and the name has been chosen on purpose to stay away from the functional feel as providing a full fledged functional type API for Vert.x future is a non goal.

**Pull request merged**
